"""
Django settings for did_annuaire_be1 project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import dj_database_url

from django.core.exceptions import ImproperlyConfigured

from config.env import APPS_DIR, BASE_DIR, env

env_path = os.path.join(BASE_DIR, ".env")
if os.path.exists(env_path):
    env.read_env(env_path)


SECRET_KEY = env.str(
    "DJANGO_SECRET_KEY",
    default="django-insecure-q2m%6pach+q1u7+8re2@_u88vu&d=zk1zc0wyv%sjavy^88&h+",
)

DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = ["*"] if DEBUG else env.list("ALLOWED_HOSTS", default=[])

LOCAL_APPS = [
    "src.api.apps.ApiConfig",
    # "src.api_keys.apps.ApiKeysConfig",
    "src.auditaction.apps.AuditactionConfig",
    "src.common.apps.CommonConfig",
    "src.dids.apps.DidsConfig",
    "src.emails.apps.EmailsConfig",
    "src.files.apps.FilesConfig",
    "src.organizations.apps.OrganizationsConfig",
    "src.seeders",
    "src.tasks.apps.TasksConfig",
    "src.users.apps.UsersConfig",
]

THIRD_PARTY_APPS = [
    "django_celery_results",
    "django_celery_beat",
    "django_extensions",
    "ninja_extra",
    "ninja_jwt",
    "ninja_jwt.token_blacklist",
    "orbit",
    # 'widget_tweaks',
    "corsheaders",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 'whitenoise.runserver_nostatic',
    *THIRD_PARTY_APPS,
    *LOCAL_APPS,
]

MIDDLEWARE = [
    "orbit.middleware.OrbitMiddleware",
    #    'request_id.middleware.RequestIdMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(APPS_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            # "libraries": {
            #    "widget_tweaks": "widget_tweaks.templatetags.widget_tweaks",
            # },
        },
    },
]


ORBIT_CONFIG = {
    "ENABLED": False,
    "SLOW_QUERY_THRESHOLD_MS": 500,
    "STORAGE_LIMIT": 1000,
    # Core watchers
    "RECORD_REQUESTS": True,
    "RECORD_QUERIES": True,
    "RECORD_LOGS": True,
    "RECORD_EXCEPTIONS": True,
    # Extended watchers
    "RECORD_COMMANDS": True,
    "RECORD_CACHE": True,
    "RECORD_MODELS": True,
    "RECORD_HTTP_CLIENT": True,
    "RECORD_MAIL": True,
    "RECORD_SIGNALS": True,
    
    # Advanced watchers (v0.5.0+)
    "RECORD_JOBS": True,
    "RECORD_REDIS": True,
    "RECORD_GATES": True,
    
    # v0.6.0 watchers
    'RECORD_TRANSACTIONS': True,
    'RECORD_STORAGE': True,
    
    #'WATCHER_FAIL_SILENTLY': True,
    
    # Security
    "AUTH_CHECK": lambda request: request.user.is_staff,
    "IGNORE_PATHS": ["/orbit/", "/static/", "/media/"],
}


WSGI_APPLICATION = "config.wsgi.application"

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
# }
DATABASE_URL = env.str("DATABASE_URL", "postgres://user:pass@localhost:5432/db")
if DATABASE_URL.startswith("postgres://") or DATABASE_URL.startswith("postgresql://"):
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=500,
            conn_health_checks=True,
        )
    }

CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])

DATABASES["default"]["ATOMIC_REQUESTS"] = True

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "users.User"

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")

FR_APP_DOMAIN = env("FR_APP_DOMAIN", default="http://localhost:3000")

from config.settings.loggers.settings import *  # noqa
from config.settings.loggers.setup import LoggersSetup  # noqa

INSTALLED_APPS, MIDDLEWARE = LoggersSetup.setup_settings(INSTALLED_APPS, MIDDLEWARE)
LoggersSetup.setup_structlog()
LOGGING = LoggersSetup.setup_logging()

from config.settings.celery import *  # noqa
from config.settings.email_sending import *  # noqa
from config.settings.files_and_storages import *  # noqa
from config.settings.jwt import *  # noqa
from config.settings.sentry import *  # noqa
from config.settings.cors import *  # noqa
# from config.settings.sessions import *  # noqa
# from config.settings.google_oauth2 import *  # noqa

# from config.settings.debug_toolbar.settings import *  # noqa
# from config.settings.debug_toolbar.setup import DebugToolbarSetup  # noqa

# INSTALLED_APPS, MIDDLEWARE = DebugToolbarSetup.do_settings(INSTALLED_APPS, MIDDLEWARE)

if not (DIDS_ROOT := env("DIDS_ROOT", default=None)):
    raise ImproperlyConfigured("DIDS_ROOT environment variable is not set")

DIDS_SIGNING_ENABLED = env.bool("DIDS_SIGNING_ENABLED", default=False)

# SITE_ID = 2
# STORAGES = {
#    "default": {
#        "BACKEND": "django.core.files.storage.FileSystemStorage",
#    },
#    "staticfiles": {
#        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#    },
# }
ADMIN_USER_NAME = env("ADMIN_USER_NAME")
ADMIN_USER_EMAIL = env("ADMIN_USER_EMAIL")

ADMINS = []

if ADMIN_USER_NAME and ADMIN_USER_EMAIL:
    ADMINS.append((ADMIN_USER_NAME, ADMIN_USER_EMAIL))
    # ADMINS.append(ADMIN_USER_EMAIL)  # Only add the email string django 6
    # ADMINS.append(f'"{ADMIN_USER_NAME}" <{ADMIN_USER_EMAIL}>')

MANAGERS = ADMINS

# Java fallback for EC explicit parameters
CERT_JAVA_FALLBACK_ENABLED = env.bool("CERT_JAVA_FALLBACK_ENABLED", default=False)
CERT_JAVA_JAR = env.str("CERT_JAVA_JAR", default="/app/bin/ecdsa-extractor.jar")
CERT_JAVA_TIMEOUT_S = env.int("CERT_JAVA_TIMEOUT_S", default=10)