# Generated by Django 5.2.10 on 2026-01-23 11:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('SUPERUSER', 'Super Utilisateur'), ('ORG_ADMIN', 'Admin Organisation'), ('ORG_MEMBER', 'Membre Organisation'), ('AUDITOR', 'Auditeur')], db_index=True, default='ORG_MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'En Attente'), ('INVITED', 'Invité'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Désactivé')], default='PENDING', max_length=20)),
                ('invitation_token', models.CharField(blank=True, db_index=True, max_length=255)),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('totp_secret', models.CharField(blank=True, max_length=255)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('email_otp_code', models.CharField(blank=True, max_length=6)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('sms_otp_code', models.CharField(blank=True, max_length=6)),
                ('sms_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('can_publish_prod', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('functions', models.CharField(blank=True, max_length=150)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organizations.organization')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(fields=('email',), name='user_email_unique')],
            },
        ),
    ]
