# Generated by Django 5.2.10 on 2026-01-28 14:20

import django.contrib.postgres.indexes
import src.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="user_email_unique",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.JSONField(
                default=list,
                help_text="List of role tokens (e.g., ['ORG_MEMBER','AUDITOR']).",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("INVITED", "Invited"),
                    ("ACTIVE", "Active"),
                    ("DEACTIVATED", "Deactivated"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["role"], name="user_role_gin", opclasses=["jsonb_path_ops"]
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_superuser", True), ("organization__isnull", True)),
                    ("is_superuser", False),
                    _connector="OR",
                ),
                name="superuser_requires_null_org",
            ),
        ),
    ]
