# Generated by Django 5.2.10 on 2026-01-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_user_email_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
