# Generated by Django 5.2.10 on 2026-01-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_otp_sent_at_user_sms_otp_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sms_otp_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
