# Generated by Django 5.2.10 on 2026-01-10 23:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "db_table": "applications",
            },
        ),
        migrations.CreateModel(
            name="DIDDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("did", models.CharField(db_index=True, max_length=500, unique=True)),
                (
                    "domain",
                    models.CharField(
                        help_text="Domaine saisi par l'utilisateur (usage futur)",
                        max_length=255,
                    ),
                ),
                ("document", models.JSONField()),
                ("version", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("PREPROD", "Pré-production"),
                            ("PUBLISHED", "Publié"),
                            ("REVOKED", "Révoqué"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("preprod_published_at", models.DateTimeField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("prod_published_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "DID Document",
                "verbose_name_plural": "DID Documents",
                "db_table": "did_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PublicKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_id", models.CharField(max_length=100)),
                (
                    "key_type",
                    models.CharField(
                        choices=[
                            ("Ed25519VerificationKey2020", "Ed25519"),
                            ("JsonWebKey2020", "JWK (RSA/EC)"),
                            ("EcdsaSecp256k1VerificationKey2019", "secp256k1"),
                            ("RsaVerificationKey2018", "RSA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("public_key_pem", models.TextField(blank=True)),
                ("public_key_jwk", models.JSONField(blank=True, null=True)),
                ("public_key_multibase", models.TextField(blank=True)),
                (
                    "certificate_file",
                    models.FileField(
                        help_text="Fichier certificat original uploadé",
                        upload_to="certificates/%Y/%m/",
                    ),
                ),
                ("controller", models.CharField(max_length=500)),
                (
                    "purposes",
                    models.JSONField(
                        default=list,
                        help_text="['authentication', 'assertionMethod', etc.]",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Public Key",
                "verbose_name_plural": "Public Keys",
                "db_table": "public_keys",
            },
        ),
    ]
