# Generated by Django 6.0.1 on 2026-01-16 08:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dids", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DidDocumentKeyBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purposes_snapshot", models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="uploadedpublickey",
            name="did_key_ref_unique",
        ),
        migrations.AddField(
            model_name="uploadedpublickey",
            name="version",
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddConstraint(
            model_name="uploadedpublickey",
            constraint=models.UniqueConstraint(
                fields=("did", "key_id", "version"), name="did_keyid_version_unique"
            ),
        ),
        migrations.AddField(
            model_name="diddocumentkeybinding",
            name="did_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_bindings",
                to="dids.diddocument",
            ),
        ),
        migrations.AddField(
            model_name="diddocumentkeybinding",
            name="uploaded_public_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doc_bindings",
                to="dids.uploadedpublickey",
            ),
        ),
        migrations.AddConstraint(
            model_name="diddocumentkeybinding",
            constraint=models.UniqueConstraint(
                fields=("did_document", "uploaded_public_key"),
                name="doc_keybinding_unique",
            ),
        ),
    ]
