# Generated by Django 5.2.10 on 2026-01-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dids", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diddocument",
            name="file_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 of published did.json (PROD)",
                max_length=64,
                null=True,
            ),
        ),
    ]
