# Generated by Django 5.2.10 on 2026-01-26 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0004_alter_diddocument_file_sha256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diddocument',
            index=models.Index(fields=['did', 'environment', 'is_active'], name='did_env_active_idx'),
        ),
    ]
