# Generated by Django 5.2.10 on 2026-01-30 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0005_diddocument_did_env_active_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='publishrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('did', 'environment'), name='unique_pending_publish_request_per_did_env'),
        ),
    ]
