# Generated by Django 5.2.10 on 2026-02-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0006_publishrequest_unique_pending_publish_request_per_did_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='compliance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
