# Generated by Django 5.2.10 on 2026-01-10 23:20

import django.utils.timezone
import src.organizations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADMINISTRATION", "Administration"),
                            ("ENTREPRISE", "Entreprise"),
                            ("PSCE", "PSCE"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                (
                    "allowed_email_domains",
                    models.JSONField(
                        default=list, help_text="Liste des domaines email autorisées"
                    ),
                ),
                (
                    "justification_document",
                    models.FileField(
                        blank=True,
                        help_text="Document de justification",
                        null=True,
                        upload_to="organizations/justifications/",
                        validators=[src.organizations.models.validate_pdf_only],
                    ),
                ),
                (
                    "authorization_document",
                    models.FileField(
                        upload_to="organizations/authorizations/",
                        validators=[src.organizations.models.validate_pdf_only],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("ACTIVE", "Actif"),
                            ("REFUSED", "Refusé"),
                            ("SUSPENDED", "Suspendu"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("refused_at", models.DateTimeField(blank=True, null=True)),
                ("refusal_reason", models.TextField(blank=True)),
                ("max_users", models.IntegerField(default=10)),
                ("max_applications", models.IntegerField(default=5)),
            ],
            options={
                "verbose_name": "Organisation",
                "verbose_name_plural": "Organisations",
                "db_table": "organizations",
            },
        ),
    ]
