# Generated by Django 5.2.10 on 2026-01-29 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status', '-created_at'], name='organizatio_status_23ff88_idx'),
        ),
    ]
