# Generated by Django 5.2.10 on 2026-01-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_refused_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='max_applications',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='max_users',
        ),
        migrations.AlterField(
            model_name='organization',
            name='authorization_document',
            field=models.FileField(help_text='Autorisation de l’organisation (document signé par le représentant légal de l’organisation)', upload_to='organizations/authorizations/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REFUSED', 'Refused'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
