# Generated by Django 5.2.10 on 2026-01-16 04:56

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('ORGANIZATION', 'Organization'), ('USER', 'User'), ('DID', 'DID'), ('KEY', 'Key'), ('API', 'API'), ('AUTH', 'Authentication'), ('SYSTEM', 'System')], default='SYSTEM', max_length=32)),
                ('action', models.CharField(choices=[('AUTH_LOGIN_SUCCESS', 'Login success'), ('AUTH_LOGIN_FAILED', 'Login Failed'), ('AUTH_LOGOUT', 'Logout'), ('ORG_CREATED', 'Organisation créée'), ('ORG_VALIDATED', 'Organisation validée'), ('ORG_REFUSED', 'Organisation refusée'), ('ORG_SUSPENDED', 'Organisation suspendue'), ('ORG_DELETED', 'Organization Deleted'), ('ORGANIZATION_TOGGLED_ACTIVATION', 'Organization status toggled'), ('USER_INVITED', 'Utilisateur invité'), ('USER_ACTIVATED', 'Utilisateur activé'), ('USER_LOGIN', 'Connexion utilisateur'), ('USER_LOGOUT', 'Déconnexion utilisateur'), ('USER_SUSPENDED', 'Utilisateur suspendu'), ('USER_CREATED', 'Création Utilisateur'), ('DID_CREATED', 'DID créé'), ('DID_PUBLISHED_DRAFT', 'DID publié en draft'), ('DID_PUBLISHED_PUBLIC', 'DID publié publiquement'), ('DID_REVOKED', 'DID révoqué'), ('KEY_UPLOADED', 'Clé/certificat ajouté'), ('KEY_DELETED', 'Clé/certificat supprimé'), ('API_KEY_CREATED', 'Clé API créée'), ('API_KEY_REVOKED', 'Clé API révoquée'), ('EMAIL_SENT', 'Email delivered'), ('EMAIL_SEND_FAILED', 'Email delivery failed')], db_index=True, max_length=50)),
                ('target_type', models.CharField(blank=True, help_text="Type de ressource: 'user', 'organization', 'did', etc.", max_length=50, null=True)),
                ('target_id', models.CharField(blank=True, help_text='ID de la ressource affectée', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Informations contextuelles supplémentaires')),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
