# Generated by Django 5.2.11 on 2026-02-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditaction', '0010_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
