# Generated by Django 5.2.11 on 2026-02-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditaction', '0011_alter_auditlog_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
